# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               halculator
tagline:             'A simple calculator written in Haskell'
description:         'Released under the <b>MIT License</b> as is, without any warranty.'
url:                 https://tim6her.github.io
baseurl:             /halculator

# About/contact
author:
  name:              Tim Herbstrith

github-repo:       https://www.github.com/tim6her/halculator

# Custom vars
version:             <a href="https://badge.fury.io/gh/tim6her%2Fhalculator"><img src="https://badge.fury.io/gh/tim6her%2Fhalculator.svg" alt="GitHub version" height="18"></a>
